# Generated by Django 3.0.7 on 2021-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expired_date',
            field=models.DateTimeField(),
        ),
    ]
