# Generated by Django 3.0.7 on 2021-08-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Al', 'البرز'), ('Te', 'تهران'), ('Az_E', 'آذربایجان شرقی'), ('Az_W', 'آذربایجان غربی'), ('Ko_N', 'خراسان شمالی'), ('Ko_S', 'خراسان جنوبی'), ('Ko_C', 'خراسان مرکزی'), ('Si', 'سیستان و بلوچستان'), ('Mar', 'مرکزی'), ('Go', 'گلستان'), ('Gi', 'گیلان'), ('Ha', 'همدان'), ('Lo', 'لرستان'), ('Ku', 'خوزستان'), ('Kerman', 'کرمان'), ('Ker', 'کرمانشاه'), ('Char', 'چهارمحال و بختیاری'), ('Es', 'اصفهان'), ('Eil', 'ایلام'), ('Bu', 'بوشهر'), ('Zan', 'زنجان'), ('Sem', 'سمنان'), ('Fars', 'فارس'), ('Ghaz', 'قزوین'), ('Ghom', 'قم'), ('Koh', 'کهگیلویه و بویراحمد'), ('Maz', 'مازندران'), ('Hor', 'هرمزگان'), ('Yaz', 'یزد')], max_length=7)),
                ('Address', models.TextField(max_length=1000)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نشانی',
                'verbose_name_plural': 'نشانی ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
