# Generated by Django 3.0.7 on 2021-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('البرز', 'Al'), ('تهران', 'Te'), ('آذربایجان شرقی', 'Az_E'), ('آذربایجان غربی', 'Az_W'), ('خراسان شمالی', 'Ko_N'), ('خراسان جنوبی', 'Ko_S'), ('خراسان مرکزی', 'Ko_C'), ('سیستان و بلوچستان', 'Si'), ('مرکزی', 'Mar'), ('گلستان', 'Go'), ('گیلان', 'Gi'), ('همدان', 'Ha'), ('لرستان', 'Lo'), ('خوزستان', 'Ku'), ('کرمان', 'Kerman'), ('کرمانشاه', 'Ker'), ('چهارمحال و بختیاری', 'Char'), ('اصفهان', 'Es'), ('ایلام', 'Eil'), ('بوشهر', 'Bu'), ('زنجان', 'Zan'), ('سمنان', 'Sem'), ('فارس', 'Fars'), ('قزوین', 'Ghaz'), ('قم', 'Ghom'), ('کهگیلویه و بویراحمد', 'Koh'), ('مازندران', 'Maz'), ('هرمزگان', 'Hor'), ('یزد', 'Yaz')], max_length=50),
        ),
    ]
