# Generated by Django 3.0.7 on 2021-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
