# Generated by Django 3.0.7 on 2021-09-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_book_number_of_sell'),
        ('orders', '0003_auto_20210903_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Book'),
        ),
    ]
