# Generated by Django 3.0.7 on 2021-09-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_is_active'),
        ('orders', '0004_auto_20210903_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add', to='users.Address'),
        ),
    ]
