# Generated by Django 3.0.7 on 2021-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
