# Generated by Django 3.0.7 on 2021-08-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-expired_date'], 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
    ]
